title:
  chinese-font: "FZXiaoBiaoSong-B05"
  latin-font: "Times New Roman"
  size: "22pt"
  color: "#000000"
  space-before: "28pt"
  space-after: "28pt"
  line-spacing: "28pt"
  numbering: null
  first-line-indent: null
  align: "center"
h1:
  chinese-font: "FZHei-B01"
  latin-font: "Times New Roman"
  size: "16pt"
  color: "#000000"
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "28pt"
  numbering: "一、"
  first-line-indent: "2em"
  align: "left"
h2:
  chinese-font: "FZKai-Z03"
  latin-font: "Times New Roman"
  size: "16pt"
  color: "#000000"
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "28pt"
  numbering: "（一）"
  first-line-indent: "2em"
  align: "left"
h3:
  chinese-font: "FZFangSong-Z02"
  latin-font: "Times New Roman"
  size: "16pt"
  color: "#000000"
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "28pt"
  numbering: "1. "
  first-line-indent: "2em"
  align: "left"
h4:
  chinese-font: "FZFangSong-Z02"
  latin-font: "Times New Roman"
  size: "16pt"
  color: "#000000"
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "28pt"
  numbering: "（1）"
  first-line-indent: "2em"
  align: "left"
body:
  chinese-font: "FZFangSong-Z02"
  latin-font: "Times New Roman"
  size: "16pt"
  color: "#000000"
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "28pt"
  first-line-indent: "2em"
  align: "left"
image:
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "1em"
  align: "center"
image-caption:
  chinese-font: "FZFangSong-Z02"
  latin-font: "Times New Roman"
  size: "16pt"
  color: "#000000"
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "28pt"
  numbering: "图1 "
  first-line-indent: null
  align: "center"
math-block:
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "1em"
  align: "center"
