title:
  chinese-font: "FZXiaoBiaoSong-B05"
  latin-font: "Times New Roman"
  size: "22pt"
  color: "#000000"
  space-before: "28pt"
  space-after: "28pt"
  line-spacing: "28pt"
  numbering: null
  hanging-indent: null
  first-line-indent: null
  indent-before-text: "0pt"
  align: "center"
h1: &h1
  chinese-font: "FZHei-B01"
  latin-font: "Times New Roman"
  size: "16pt"
  color: "#000000"
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "28pt"
  numbering: "一、"
  hanging-indent: null
  first-line-indent: "2em"
  indent-before-text: "0pt"
  align: "left"
h2:
  <<: *h1
  chinese-font: "FZKai-Z03"
  numbering: "（一）"
h3:
  <<: *h1
  chinese-font: "FZFangSong-Z02"
  numbering: "1. "
h4:
  <<: *h1
  chinese-font: "FZFangSong-Z02"
  numbering: "（1）"
body: &body
  chinese-font: "FZFangSong-Z02"
  latin-font: "Times New Roman"
  size: "16pt"
  color: "#000000"
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "28pt"
  numbering: null
  hanging-indent: null
  first-line-indent: "2em"
  indent-before-text: "0pt"
  align: "justify"
image:
  chinese-font: null
  latin-font: null
  size: null
  color: null
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "1em"
  numbering: null
  hanging-indent: null
  first-line-indent: null
  indent-before-text: "0pt"
  align: "center"
image-caption:
  <<: *body
  numbering: "图1 "
  first-line-indent: null
  align: "center"
ordered-list:
  <<: *body
  numbering: "1. "
  hanging-indent: "2em"
  first-line-indent: null
  indent-before-text: "2em"
  indent-before-text-increment: "2em"
unordered-list:
  <<: *body
  numbering: "- "
  hanging-indent: "2em"
  first-line-indent: null
  indent-before-text: "2em"
  indent-before-text-increment: "2em"
inline-math: &inline-math
  <<: *body
  chinese-font: null
  latin-font: "cm"
math-block:
  <<: *inline-math
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "1em"
  first-line-indent: null
  align: "center"
inline-code: &inline-code
  <<: *body
  chinese-font: "Microsoft YaHei"
  latin-font: "Consolas"
code-block:
  <<: *inline-code
  space-before: "0pt"
  space-after: "0pt"
  line-spacing: "1em"
  first-line-indent: null
  indent-before-text: "2em"
  align: "left"
table-header:
  <<: *body
  first-line-indent: null
  align: "center"
table-body:
  <<: *body
  first-line-indent: null
  align: "left"
